//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t say_hello(int32_t str2);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // 0x804a040
int32_t g2 = 0; // 0x804a060
struct _IO_FILE * g3 = NULL; // 0x804a064
int32_t g4;

// ------------------------ Functions -------------------------

// Address range: 0x80485fb - 0x8048639
int32_t say_hello(int32_t str2) {
    // 0x80485fb
    int32_t str; // bp-132, 0x80485fb
    strcpy((char *)&str, (char *)str2);
    printf("Hello, ");
    printf((char *)&str);
    return puts("!");
}

// Address range: 0x8048639 - 0x80486ff
int main(int argc, char ** argv) {
    // 0x8048639
    setbuf(g3, NULL);
    setbuf((struct _IO_FILE *)g2, NULL);
    setbuf((struct _IO_FILE *)g1, NULL);
    int32_t * mem = malloc(0); // 0x8048678
    puts("What's your name?");
    int32_t v1; // bp-16, 0x8048639
    int32_t v2 = &v1; // 0x804868d
    int32_t * v3 = (int32_t *)(v2 - 4);
    int32_t v4; // bp-13, 0x8048639
    int32_t v5 = &v4; // 0x8048693
    int32_t * v6 = (int32_t *)(v2 - 8); // 0x8048694
    *v3 = v5;
    *v6 = (int32_t)"%c";
    scanf((char *)&g4);
    *v3 = 1;
    *v6 = (int32_t)mem;
    int32_t * mem2 = realloc(&g4, (int32_t)&g4); // 0x80486ac
    int32_t v7 = (int32_t)mem2;
    char v8 = v4; // 0x80486bb
    int32_t v9 = v7; // 0x80486bd
    char * v10 = (char *)mem2; // 0x80486bd
    if (v8 != 10) {
        int32_t v11 = 1;
        *(char *)mem2 = v8;
        *v3 = v5;
        *v6 = (int32_t)"%c";
        scanf((char *)&g4);
        int32_t v12 = v11 + 1; // 0x80486a1
        *v3 = v12;
        *v6 = v7;
        int32_t mem3 = (int32_t)realloc(&g4, (int32_t)&g4);
        char v13 = v4; // 0x80486bb
        char * v14 = (char *)(v11 + mem3);
        v9 = mem3;
        v10 = v14;
        while (v13 != 10) {
            // 0x80486ea
            v11 = v12;
            *v14 = v13;
            *v3 = v5;
            *v6 = (int32_t)"%c";
            scanf((char *)&g4);
            v12 = v11 + 1;
            *v3 = v12;
            *v6 = mem3;
            mem3 = (int32_t)realloc(&g4, (int32_t)&g4);
            v13 = v4;
            v14 = (char *)(v11 + mem3);
            v9 = mem3;
            v10 = v14;
        }
    }
    // 0x80486bf
    *v10 = 0;
    *v3 = v9;
    say_hello(v9);
    *v3 = v9;
    free(&g4);
    return 0;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 2

