/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
__int64 sub_400590(); // weak
// int puts(const char *s);
// int setresgid(__gid_t rgid, __gid_t egid, __gid_t sgid);
// int __libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// char *fgets(char *s, int n, FILE *stream);
// __int64 __gmon_start__(void); weak
// __int64 __fastcall gets(_QWORD); weak
// int fflush(FILE *stream);
// __gid_t getegid(void);
// FILE *fopen(const char *filename, const char *modes);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
__int64 deregister_tm_clones();
__int64 register_tm_clones();
__int64 _do_global_dtors_aux(); // weak
__int64 frame_dummy();
int win();
int vuln();
int __fastcall main(int argc, const char **argv, const char **envp);
void _libc_csu_fini(); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _libc_csu_init;
__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_601010)(void) = NULL; // weak
FILE *stdout; // idb
char completed_6982; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (0000000000400570) ----------------------------------------------------
// Alternative name is '_init'
void *init_proc()
{
  void *result; // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (void *)__gmon_start__();
  return result;
}
// 4005E0: using guessed type __int64 __gmon_start__(void);

//----- (0000000000400590) ----------------------------------------------------
__int64 sub_400590()
{
  return qword_601010();
}
// 400590: using guessed type __int64 sub_400590();
// 601010: using guessed type __int64 (*qword_601010)(void);

//----- (0000000000400630) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  __libc_start_main(
    (int (*)(int, char **, char **))main,
    v4,
    &retaddr,
    (void (*)())_libc_csu_init,
    _libc_csu_fini,
    a3,
    &v5);
  __halt();
}
// 400636: positive sp value 8 has been found
// 40063D: variable 'v3' is possibly undefined

//----- (0000000000400660) ----------------------------------------------------
__int64 deregister_tm_clones()
{
  __int64 result; // rax

  result = 6295671LL - (_QWORD)&stdout;
  if ( (unsigned __int64)(6295671LL - (_QWORD)&stdout) > 0xE )
    return 0;
  return result;
}

//----- (0000000000400690) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0;
}

//----- (00000000004006D0) ----------------------------------------------------
__int64 _do_global_dtors_aux()
{
  __int64 result; // rax

  if ( !completed_6982 )
  {
    result = deregister_tm_clones();
    completed_6982 = 1;
  }
  return result;
}
// 4006D0: using guessed type __int64 _do_global_dtors_aux();
// 601078: using guessed type char completed_6982;

//----- (00000000004006F0) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 4006F0: could not find valid save-restore pair for rbp

//----- (000000000040071D) ----------------------------------------------------
int win()
{
  char s[136]; // [rsp+0h] [rbp-90h] BYREF
  FILE *stream; // [rsp+88h] [rbp-8h]

  stream = fopen("flag.txt", "r");
  fgets(s, 128, stream);
  puts(s);
  return fflush(stdout);
}

//----- (0000000000400773) ----------------------------------------------------
int vuln()
{
  char s[160]; // [rsp+0h] [rbp-A0h] BYREF

  gets(s);
  puts(s);
  return fflush(stdout);
}
// 4005F0: using guessed type __int64 __fastcall gets(_QWORD);

//----- (00000000004007AD) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  __gid_t rgid; // [rsp+1Ch] [rbp-4h]

  rgid = getegid();
  setresgid(rgid, rgid, rgid);
  puts("Enter a string: ");
  fflush(stdout);
  vuln();
  return 0;
}

//----- (0000000000400810) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // rbx
  signed __int64 v4; // rbp

  v3 = 0;
  v4 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v4 )
  {
    do
      _frame_dummy_init_array_entry[v3++]();
    while ( v3 != v4 );
  }
}
// 600E10: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 600E18: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000400884) ----------------------------------------------------
// Alternative name is '_fini'
void term_proc()
{
  ;
}

// nfuncs=31 queued=12 decompiled=12 lumina nreq=0 worse=0 better=0
// ALL OK, 12 function(s) have been successfully decompiled
